name: Build and Deploy to S3

on:
  push:
    branches: [ master ]

concurrency:
  group: "s3"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.17
    - name: Build for Windows
      run: GOOS=windows GOARCH=amd64 go build -o builds/textadventure-windows.exe
    - name: Build for Mac 
      run: GOOS=darwin GOARCH=amd64 go build -o builds/textadventure-mac.run
    - name: Build for Linux 
      run: GOOS=linux GOARCH=amd64 go build -o builds/textadventure-linux.run
    - name: Upload artifact
      uses: actions/upload-artifact@v1
      with:
        name: Bulid
        path: ./builds/
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Download artifact
      uses: actions/download-artifact@v1
      with:
        name: Bulid
        path: ./builds/
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: eu-west-2
    - name: Copy files to S3
      run: |
        aws s3 sync ./builds ${{ secrets.AWS_S3_BUCKET }}/textadventure/assets/
