name: Go

on:
  push:
    branches: [ master ]

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.17
    - name: Build for Windows
      run: GOOS=windows GOARCH=amd64 go build -o builds/Windows.exe
    - name: Build for Mac 
      run: GOOS=darwin GOARCH=amd64 go build -o builds/Mac
    - name: Build for Linux 
      run: GOOS=linux GOARCH=amd64 go build -o builds/Linux
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: eu-west-2
    - name: Copy files to the website with the AWS CLI
      run: |
        aws s3 sync ./builds ${{ secrets.AWS_S3_BUCKET }}/games/text/builds
    - name: Send mail
      uses: dawidd6/action-send-mail@v3
      with:
         # Required mail server address:
        server_address: smtp.gmail.com
        # Required mail server port:
        server_port: 465  
        # Optional (recommended): mail server username:
        username: ${{secrets.MAIL_USERNAME}}
        # Optional (recommended) mail server password:
        password: ${{secrets.MAIL_PASSWORD}}
       # Required mail subject:
        subject: Github Actions - Pulbish and build of ${{github.repository}} completed sucsessfully!
      # Required recipients' addresses:
        to: ${{secrets.MAIL_USERNAME}}
      # Required sender full name (address can be skipped):
        from: headb
      # Optional whether this connection use TLS (default is true if server_port is 465)
        secure: true  
      # Optional plain body:
        body: Build and Publish job of ${{github.repository}} completed successfully!
